---
title: "T-REX Analysis on COVID Data"
author: "Sierra Barone"
contributors: "Claire Cross, and Cass Mayeda"
date: "07/07/2022"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

## Tracking Responders Expanding 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Data from Brodin lab in Rodriguez et al., Cell Rep Med. 2020 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7405891/)

# uncomment lines below to install packages
# if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
# BiocManager::install("cytoMEM")
# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# install.packages("ggplot2", repos = "http://cran.us.r-project.org")
# install.packages("FNN", repos = "http://cran.us.r-project.org")
# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# install.packages("uwot", repos = "http://cran.us.r-project.org")
# install.packages("dbscan", repos = "http://cran.us.r-project.org")
# if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
# BiocManager::install("flowCore")
# BiocManager::install("Biobase")


# load packages
library(flowCore)
library(uwot)
library(FNN)
library(ggplot2)
library(dbscan)
library(cytoMEM)
library(tidyverse)
library(Biobase)
library(RColorBrewer)
library(dplyr)
library(purrr)
library(cowplot)

# set working directory 
setwd(paste(getwd(),"/data_files/brodin covid", sep = ""))

# setup sample and T-REX info
output_filename = "_T-REX"
sample_type = "COV"
sample_id = "35"
time_comparison = "0v4" 
kvalue = 60

# look at files
data.files <-  dir(pattern = "*.fcs")
print(data.files)

# choose index for each timepoint based on order of data.files
first.timepoint = 1
second.timepoint = 2

# combine paired samples
first.timepoint.data = as.data.frame(lapply(lapply(data.files[[first.timepoint]], read.FCS), exprs))
first.timepoint.data$orig_ID = first.timepoint
first.timepoint.data$File_ID = 1
second.timepoint.data = as.data.frame(lapply(lapply(data.files[[second.timepoint]], read.FCS), exprs))
second.timepoint.data$orig_ID = second.timepoint
second.timepoint.data$File_ID = 2
paired.data = rbind(first.timepoint.data,second.timepoint.data)
orig.names <- colnames(paired.data)
colnames(paired.data)[1:(length(paired.data) - 2)] <- as.character(read.FCS(data.files[[1]])@parameters@data[["desc"]])
```

```{r equal_sampling}
# set seed and equally sample based on limiting sample
set.seed(1)
files.to.sample = split(paired.data,paired.data$`File_ID`)
sampled.data <- list()
for (i in 1: length(files.to.sample)){
    sampled.data[[i]] = as.data.frame(files.to.sample[[i]][sample(nrow(files.to.sample[[i]]), min(sapply(files.to.sample, nrow))), ])}
my.sampled.data = as.data.frame(do.call(rbind, sampled.data))
```

```{r scaling_and_filtering}
# choose markers to make low dimensional projection of the data and scale them accordingly 
#colnames(my.sampled.data)   
my.chosen.sampled.data = my.sampled.data[,c(3,9:14,19:31,33:54,57:61)]
#colnames(my.chosen.sampled.data) 
transformed.data = as.data.frame(t(apply(my.chosen.sampled.data, 1, function(x) asinh(x/5))))
colnames(transformed.data) 
umap.input = transformed.data
```

```{r UMAP}
setwd(paste(getwd(),"/data_files/brodin covid", sep = ""))

# run UMAP amd save model
myumap <- umap(umap.input, ret_model = TRUE, verbose = TRUE)
dir.create("./output files/")
#save_uwot(myumap, paste0(strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"_umap_model_results"))
umap.data = as.data.frame(myumap$embedding)
colnames(umap.data) <- c("UMAP1", "UMAP2")
```

```{r KNN}
setwd(paste(getwd(),"/data_files/brodin covid", sep = ""))

# KNN search per cell 
neighbor_index = knnx.index(umap.data,umap.data,k=kvalue)
neighbor_index[neighbor_index <= nrow(umap.data)/2] <- 0
neighbor_index[neighbor_index > nrow(umap.data)/2] <- 1
# calculate percent change in each KNN region
percent_change = (rowSums(neighbor_index) / kvalue * 100)

# binning and plot info
all.data = cbind(my.sampled.data, umap.data,percent_change)
range <- apply(apply(umap.data, 2, range), 2, diff)
graphical.ratio <- (range[1] / range[2])
test.round = round(percent_change)
trex.plot <-
  data.frame(x = umap.data[, 1], y = umap.data[, 2], col = test.round)
trex.plot$cuts <- ifelse(trex.plot$col>=95, '[95,100]', ifelse(trex.plot$col>=85,'[85,95)', ifelse(trex.plot$col<=5,'[0,5]', ifelse(trex.plot$col<=15,'(5,15]','(15,85)'))))
ordered_plot = trex.plot[order(trex.plot$cuts), ]

# create T-REX plot
png(
  paste(
    "./output files/",
    strftime(Sys.time(), "%Y-%m-%d_%H%M%S"),
    " blue red TREX plot.png",
    sep = ""
  ),
  res = 200,
  width = 1500,
  height = 1500
)

final_trex_plot <-
  ggplot(ordered_plot) + 
  geom_point(aes(x = x, y = y, colour = cuts), cex = 1) +
  coord_fixed(ratio = graphical.ratio) +
  scale_color_manual(
    labels = c("\u2265 95% from 1st timepoint",
               "85-95% from 1st timepoint",
               "from 1st and 2nd timepoints",
               "85-95% from 2nd timepoint",
               "\u2265 95% from 2nd timepoint"), 
    values = c(
      "[0,5]" = "navyblue",
      "(5,15]" = "lightskyblue",
      "(15,85)" = "lightgray",
      "[85,95)" = "lightcoral",
      "[95,100]" = "darkred"
    )
  ) +
  guides(color = guide_legend(override.aes = list(size = 4))) + 
  labs(x = "UMAP1", y = "UMAP2",
       title = paste(sample_type,"_",sample_id,"_",time_comparison," - Percent Change",sep = ""),
       caption = "Data from Brodin lab in Rodriguez et al., Cell Rep Med. 2020") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_blank())

print(final_trex_plot)
dev.off()
final_trex_plot
```
  
```{r trex_results}  
setwd(paste(getwd(),"/data_files/brodin covid", sep = ""))

umap.bychannel <- as_tibble(umap.data) %>%
  bind_cols(transformed.data)  %>%
  gather(channel, intensity, -UMAP1, -UMAP2) %>%
  mutate(across(channel, factor)) %>%
  group_split(channel) %>%
  map(
    ~ggplot(., aes(x = UMAP1, y = UMAP2, col = intensity)) +
      geom_point(shape = ".", size = 8) +
      scale_color_gradientn(
        colours = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(5)) +
      facet_grid(~ channel, labeller = function(x) label_value(x, multi_line = FALSE)) +
      coord_fixed() +
      theme_bw() +
      theme(strip.text.x = element_text(size = 20),
            legend.title=element_blank())) %>%
  plot_grid(plotlist = ., align = 'hv', ncol = 8)

png(paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"UMAP on transformed data.png"),height = 2000,width = 4000)
print(umap.bychannel)
dev.off()

# uncomment lines below to plot heat on markers on umap axes
# plot.to.output<-list()
# for (i in 1:ncol(umap.input)){
#   color.plot <- data.frame(x = umap.data[,1], y = umap.data[,2], col = umap.input[,c(i)])
#   order.plot <- color.plot[order(color.plot$col),]
#   print(ggplot(order.plot) + 
#           geom_point(aes(x = x, y = y, col = col), cex = 0.1, shape = 1) + 
#           coord_fixed(ratio = graphical.ratio) +
#           scale_color_gradientn(colours = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(50)) + 
#           labs(x = "UMAP1", y = "UMAP2", col = colnames(umap.input)[i]) +
#           theme_bw() + 
#           theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
#         )
# }

# calculate degree of change and direction of change for individual pairwise comparison
all.data$status <- trex.plot$cuts
sample.table <- data.frame(sample_type,sample_id,time_comparison,total_cells = nrow(umap.data))
summary_stats<-c(sum(trex.plot$cuts == '(15,85)'),sum(trex.plot$cuts == '(5,15]'),sum(trex.plot$cuts == '[0,5]'),sum(trex.plot$cuts == '[85,95)'),sum(trex.plot$cuts == '[95,100]'))

sample.table[,c(5:9)]<-summary_stats
colnames(sample.table)[5:9]<-c( "(15,85)", "(5,15]", "[0,5]", "[85,95)", "[95,100]")
percent = 100*(summary_stats/ nrow(trex.plot))

sample.table$degree_of_change = (sum(percent[3]+percent[5]))
sample.table$direction_of_change = (summary_stats[5]-summary_stats[3]) / (summary_stats[5]+summary_stats[3])

write.csv(sample.table, paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"_trex_results.csv"))
print(sample.table)
```

```{r clustering}
setwd(paste(getwd(),"/data_files/brodin covid", sep = ""))

# use DBSCAN to cluster on regions of great change (5th and 95 percentiles of change)
regions.of.interest <- all.data %>%
  dplyr::filter(status == "[0,5]" | status == "[95,100]")
regions.of.interest.umap = cbind(regions.of.interest$UMAP1,regions.of.interest$UMAP2)
a = dbscan::dbscan(regions.of.interest.umap, eps = 0.3,minPts = 1)
cluster = a$cluster 
track.data = cbind(regions.of.interest,cluster)
track.data <- track.data %>%
  filter(cluster!=0)

track.data$cluster[which( track.data$status=="[0,5]")]<- paste0(track.data$cluster[which(track.data$status=="[0,5]")],"05")
track.data$cluster[which( track.data$status=="[95,100]")]<-paste0(track.data$cluster[which( track.data$status=="[95,100]")],"95")
track.data$cluster<-as.numeric(track.data$cluster)
cluster.data = split(track.data,track.data$cluster)
median.percent.change = lapply(cluster.data, function(x) median(x[,which(colnames(track.data)=="percent_change")]))
mean.percent.change = lapply(cluster.data, function(x) mean(x[,which(colnames(track.data)=="percent_change")]))
write.csv(mean.percent.change,paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," DBSCAN_cluster_average_percent_change.csv",sep =""))


library(RColorBrewer)
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
values = sample(col_vector)

png(paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," DBSCAN_plot.png",sep =""),res = 200, width = 1500, height = 1500)
dbscan_plot <- 
  ggplot(data.frame(x = track.data$UMAP1, y = track.data$UMAP2, col = as.factor(track.data$cluster))) + 
  coord_fixed(ratio = graphical.ratio) + 
  geom_point(aes(x = x, y = y, color = col), cex = 1.5) + 
  scale_color_manual(values = values) + 
  guides(colour = guide_legend(override.aes = list(size = 5), nrow = 13)) +
  labs(x = "UMAP 1", y = "UMAP 2", color = "DBSCAN Cluster") + 
  theme_bw() + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_blank())

print(dbscan_plot)
dev.off()
dbscan_plot
```

```{r MEM}
setwd(paste(getwd(),"/data_files/brodin covid", sep = ""))

# run MEM on DBSCAN clusters split by 95th and 5th percentiles of change in KNN region
MEM.data = track.data[,c(3,9:14,19:31,33:54,57:61,ncol(track.data))]
MEM.data = MEM.data[order(MEM.data$cluster),]
MEM.values.KNN = MEM(MEM.data, transform = TRUE, cofactor = 5,
                     choose.markers = FALSE, markers = "all", choose.ref = FALSE, zero.ref = TRUE, rename.markers = FALSE,
                     new.marker.names = "none", file.is.clust = FALSE, add.fileID = FALSE, IQR.thresh = NULL,scale.matrix = "arcsinh",scale.factor = 1)
build_heatmaps(MEM.values.KNN, cluster.MEM = "none", cluster.medians = "none",
               display.thresh = 1,  output.files = TRUE, labels = FALSE)
all.clusters = split(track.data,as.factor(track.data$cluster))
counts.total  <- sapply(all.clusters, NROW)
counts.5<-vector()
for (i in 1:length(all.clusters)){
  counts.5[i] = sum(all.clusters[[i]][["status"]] == '[0,5]')}
counts.95 = counts.total-counts.5
cluster.data = as.data.frame(counts.total)
colnames(cluster.data)<- "total_counts"
cluster.data$counts_5<-counts.5
cluster.data$counts_95<-counts.95
write.csv(cluster.data,paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," DBSCAN_cluster_percentiles_counts_MEM.csv",sep =""))
print(cluster.data)
```

```{r export_FCS_files}
setwd(paste(getwd(),"/data_files/brodin covid", sep = ""))

# export new FCS files with sampled data, percent change, and umap axes
to.export = cbind(my.sampled.data,umap.data,percent_change)
desc = colnames(to.export)[-c(ncol(my.sampled.data),(ncol(my.sampled.data)-1))]
colnames(to.export)[1:ncol(my.sampled.data)]<-orig.names
separate.fcs.files = split(to.export,to.export$`orig_ID`)
for (i in 1:length(separate.fcs.files)){
reduce.data = subset(separate.fcs.files[[i]], select=-c(`File_ID`,`orig_ID`))
mat.input<- as.matrix(reduce.data)
metadata <- data.frame(name = dimnames(mat.input)[[2]], desc = desc)
metadata$range <- apply(apply(mat.input, 2, range), 2, diff)
metadata$minRange <- apply(mat.input, 2, min)
metadata$maxRange <- apply(mat.input, 2, max)
input.flowframe <- new("flowFrame", exprs=mat.input,parameters = AnnotatedDataFrame(metadata))  
newname  = str_remove(data.files[i], ".fcs")
new.filename = paste0("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"_",newname,"_T-REX.fcs",sep="")
write.FCS(input.flowframe,filename = new.filename)
print(paste("FCS file ",i," done", sep = ""))}

# print session information
sessionInfo()
```
