---
title: "T-REX Analysis on COVID Vaccine Data"
author: "Sierra Barone"
date: "03/02/2021"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

## Tracking Responders Expanding 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Data from Kramer et al., bioRxiv. 2021 (https://doi.org/10.1101/2021.07.28.453981)

# load packages
library(flowCore)
library(uwot)
library(FNN)
library(ggplot2)
library(dbscan)
library(MEM)
library(tidyverse)
library(Biobase)

# set working directory 
setwd(paste(getwd(),"/data_files/covid vaccine", sep = ""))

# setup sample and T-REX info
output_filename = "_T-REX"
sample_type = "HIDI_COVID_Vaccine"
sample_id = "VCV_016"
time_comparison = "Post v Pre" 
kvalue = 60

# look at files
data.files <-  dir(pattern = "*.fcs")
print(data.files)
# choose index for each timepoint based on order of data.files
first.timepoint = 1
second.timepoint = 2

# combine paired samples
first.timepoint.data = as.data.frame(lapply(lapply(data.files[[first.timepoint]], read.FCS), exprs))
first.timepoint.data$orig_ID = first.timepoint
first.timepoint.data$File_ID = 1
second.timepoint.data = as.data.frame(lapply(lapply(data.files[[second.timepoint]], read.FCS), exprs))
second.timepoint.data$orig_ID = second.timepoint
second.timepoint.data$File_ID = 2
paired.data = rbind(first.timepoint.data,second.timepoint.data)
orig.names <- colnames(paired.data)
colnames(paired.data)[1:(length(paired.data) - 2)] <- as.character(read.FCS(data.files[[1]])@parameters@data[["desc"]])
```

```{r equal_sampling}
# set seed and equally sample based on limiting sample
set.seed(1)
files.to.sample = split(paired.data,paired.data$`File_ID`)
sampled.data <- list()
for (i in 1: length(files.to.sample)){
    sampled.data[[i]] = as.data.frame(files.to.sample[[i]][sample(nrow(files.to.sample[[i]]), min(sapply(files.to.sample, nrow))), ])}
my.sampled.data = as.data.frame(do.call(rbind, sampled.data))
```

```{r scaling_and_filtering}
# choose markers to make low dimensional projection of the data and scale them accordingly 
#colnames(my.sampled.data)   
my.chosen.sampled.data = my.sampled.data[,c(3,8,10:14,16,27,29,33:38,42,44:46,50,52:53,55:60,62,70)]
#colnames(my.chosen.sampled.data) 
cofactor = c(45,15,10,10,10,15,5,15,25,15,15,15,15,15,25,25,15,15,25,15,15,45,15,15,45,25,25,15,25,15,25)

transformed.data = as.data.frame(t(apply(my.chosen.sampled.data, 1, function(x) asinh(x/cofactor))))
colnames(transformed.data) 
umap.input = transformed.data
```

```{r UMAP}
setwd(paste(getwd(),"/data_files/covid vaccine", sep = ""))

dir.create("./output files/")
umap.data = as.data.frame(cbind(my.sampled.data$tSNE1,my.sampled.data$tSNE2))
colnames(umap.data) <- c("tSNE1", "tSNE2")
```

```{r KNN}
setwd(paste(getwd(),"/data_files/covid vaccine", sep = ""))

# KNN search per cell 
neighbor_index = knnx.index(umap.data,umap.data,k=kvalue)
neighbor_index[neighbor_index <= nrow(umap.data)/2] <- 0
neighbor_index[neighbor_index > nrow(umap.data)/2] <- 1
# calculate percent change in each KNN region
percent_change = (rowSums(neighbor_index) / kvalue * 100)

# binning and plot info


#### HERE #### ADD PERCENT_CHANGE
all.data = cbind(my.sampled.data, percent_change)
range <- apply(apply(umap.data, 2, range), 2, diff)
graphical.ratio <- (range[1] / range[2])
test.round = round(percent_change)
trex.plot <-
  data.frame(x = umap.data[, 1], y = umap.data[, 2], col = test.round)
trex.plot$cuts = cut(trex.plot$col, c(0, 5, 15, 85, 95, 100), include.lowest = TRUE, right = FALSE)
trex.plot$cuts = factor(trex.plot$cuts,
                        levels = c("[15,85)", "[5,15)", "[0,5)", "[85,95)", "[95,100]"))
ordered_plot = trex.plot[order(trex.plot$cuts), ]
range <- apply(apply(umap.data, 2, range), 2, diff)
graphical.ratio <- (range[1] / range[2])

# create T-REX plot
png(
  paste(
    "./output files/",
    strftime(Sys.time(), "%Y-%m-%d_%H%M%S"),
    " blue red TREX plot.png",
    sep = ""
  ),
  res = 200,
  width = 1500,
  height = 1500
)

final_trex_plot <-
  ggplot(ordered_plot) + geom_point(aes(x = x, y = y, colour = cuts), cex = 1) +
  scale_color_manual(
    name = "col",
    values = c(
      "[15,85)" = "lightgray",
      "[5,15)" = "lightskyblue",
      "[0,5)" = "navyblue",
      "[85,95)" = "lightcoral",
      "[95,100]" = "darkred"
    )
  ) +
  theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank()) +
  labs (x = "tSNE1", y = "tSNE2", title = paste(sample_type,"_",sample_id,"_",time_comparison," - Percent Change",sep = "")) + coord_fixed(ratio = graphical.ratio) + theme(legend.title = element_blank()) + 
  labs(caption = "Data from Kramer et al., bioRxiv. 2021")

print(final_trex_plot)
dev.off()
final_trex_plot
```
  
```{r trex_results}  
setwd(paste(getwd(),"/data_files/covid vaccine", sep = ""))

# uncomment lines below to plot heat on markers on umap axes
#plot.to.output<-list() 
# for (i in 1:ncol(umap.input)){
#   color.plot <- data.frame(x = umap.data[,1], y = umap.data[,2], col = umap.input[,c(i)])
#   order.plot <- color.plot[order(color.plot$col),]
#   print(ggplot(order.plot)+ geom_point(aes(x= x, y= y, col = col),cex = 0.1,shape = 1) + coord_fixed(ratio=graphical.ratio) + 
#   theme_bw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
#     labs (x = "tSNE1", y = "tSNE2", col = colnames(umap.input)[i])+
#   scale_color_gradientn(
#     colours = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(50)))}

# calculate degree of change and direction of change for individual pairwise comparison
all.data$status <- trex.plot$cuts
sample.table <- data.frame(sample_type,sample_id,time_comparison,total_cells = nrow(umap.data))
sample.table[,c(5:9)]<-summary(trex.plot$cuts)
colnames(sample.table)[5:9]<-c( "[15,85)", "[5,15)", "[0,5)", "[85,95)", "[95,100]")
percent = 100*(summary(trex.plot$cuts)/nrow(umap.data))
sample.table$degree_of_change = (sum(percent[3]+percent[5]))
sample.table$direction_of_change = (summary(trex.plot$cuts)[5]-summary(trex.plot$cuts)[3]) / (summary(trex.plot$cuts)[5]+summary(trex.plot$cuts)[3])

write.csv(sample.table, paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"_trex_results.csv"))
print(sample.table)
```

```{r clustering}
setwd(paste(getwd(),"/data_files/covid vaccine", sep = ""))

# use DBSCAN to cluster on regions of great change (5th and 95 percentiles of change)
regions.of.interest <- all.data %>%
  dplyr::filter(status == "[0,5)" | status == "[95,100]") 
regions.of.interest.umap = cbind(regions.of.interest$tSNE1,regions.of.interest$tSNE2)
a = dbscan::dbscan(regions.of.interest.umap, eps = 4,minPts = 1)
cluster = a$cluster 
track.data = cbind(regions.of.interest,cluster)
track.data <- track.data %>%
  filter(cluster!=0)

track.data$cluster[which(track.data$status=="[0,5)")]<-paste0(track.data$cluster[which(track.data$status=="[0,5)")],"05")
track.data$cluster[which(track.data$status=="[95,100]")]<-paste0(track.data$cluster[which(track.data$status=="[95,100]")],"95")
track.data$cluster<-as.numeric(track.data$cluster)

###### HERE ######## ADD ######
cluster.data = split(track.data,track.data$cluster)
median.percent.change = lapply(cluster.data, function(x) median(x[,which(colnames(track.data)=="percent_change")]))
mean.percent.change = lapply(cluster.data, function(x) mean(x[,which(colnames(track.data)=="percent_change")]))
write.csv(mean.percent.change,paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," DBSCAN_cluster_average_percent_change.csv",sep =""))


library(RColorBrewer)
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
  col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors,
                             rownames(qual_col_pals)))
  values = sample(col_vector)


png(paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," DBSCAN_plot.png",sep =""),res = 200, width = 1500, height = 1500)
dbscan_plot <- ggplot(data.frame(x = track.data$tSNE1, 
                   y = track.data$tSNE2, 
                   col = as.factor(track.data$cluster))) + coord_fixed(ratio = graphical.ratio) + 
  geom_point(aes(x=x, y=y, color=col),cex = 1.5) + 
  guides(colour = guide_legend(override.aes = list(size=5), nrow = 13)) +
  labs(x = "t-SNE 1", y = "t-SNE 2",title = "DBSCAN Clusters (5th & 95th percentiles)", 
       color = "DBSCAN Cluster") + theme_bw() + theme(legend.title = element_blank()) + scale_color_manual(values = values)
print(dbscan_plot)
dev.off()
dbscan_plot
```

```{r MEM}
setwd(paste(getwd(),"/data_files/covid vaccine", sep = ""))

# run MEM on DBSCAN clusters split by 95th and 5th percentiles of change in KNN region
MEM.data = track.data[,c(3,8,10:14,16,27:31,33:38,40,42,44:50,52:62,70,ncol(track.data))]
MEM.data = MEM.data[order(MEM.data$cluster),]
cofactor = c(45
,15
,10
,10
,10
,15
,5
,15
,25
,25
,15
,15
,15
,15
,15
,15
,15
,25
,25
,15
,15
,15
,25
,15
,25
,25
,15
,15
,45
,15
,15
,15
,45
,25
,25
,15
,25
,25
,15
,25,1)
MEM.data.transformed = as.data.frame(t(apply(MEM.data, 1, function(x) asinh(x/cofactor))))
MEM.data.transformed[,41]<-MEM.data[,41]
MEM.values.KNN = MEM(MEM.data, transform = FALSE, cofactor = 0,
                     choose.markers = FALSE, markers = "all", choose.ref = FALSE, zero.ref = TRUE, rename.markers = FALSE,
                     new.marker.names = "none", file.is.clust = FALSE, add.fileID = FALSE, IQR.thresh = NULL,scale.matrix = "arcsinh",scale.factor = 1)
build.heatmaps(MEM.values.KNN, cluster.MEM = "none", cluster.medians = "none",
               display.thresh = 1, newWindow.heatmaps=FALSE, output.files = TRUE, labels = FALSE)
all.clusters = split(track.data,as.factor(track.data$cluster))
counts.total  <- sapply(all.clusters, NROW)
counts.5<-vector()
for (i in 1:length(all.clusters)){
  counts.5[i] = summary(all.clusters[[i]]$status)[3]}
counts.95 = counts.total-counts.5
cluster.data = as.data.frame(counts.total)
colnames(cluster.data)<- "total_counts"
cluster.data$counts_5<-counts.5
cluster.data$counts_95<-counts.95
write.csv(cluster.data,paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," DBSCAN_cluster_percentiles_counts_MEM.csv",sep =""))
print(cluster.data)
```


```{r export_FCS_files}
setwd(paste(getwd(),"/data_files/covid vaccine", sep = ""))

# export new FCS files with sampled data, percent change, and umap axes
to.export = cbind(my.sampled.data,umap.data,percent_change)
desc = colnames(to.export)[-c(ncol(my.sampled.data))]
colnames(to.export)[1:ncol(my.sampled.data)]<-orig.names
separate.fcs.files = split(to.export,to.export$`File_ID`)
for (i in 1:length(separate.fcs.files)){
reduce.data = subset(separate.fcs.files[[i]], select=-c(`File_ID`))
mat.input<- as.matrix(reduce.data)
metadata <- data.frame(name = dimnames(mat.input)[[2]], desc = desc)
metadata$range <- apply(apply(mat.input, 2, range), 2, diff)
metadata$minRange <- apply(mat.input, 2, min)
metadata$maxRange <- apply(mat.input, 2, max)
input.flowframe <- new("flowFrame", exprs=mat.input,parameters = AnnotatedDataFrame(metadata))  
newname  = str_remove(data.files[i], ".fcs")
new.filename = paste0("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"_",newname,"_T-REX.fcs",sep="")
write.FCS(input.flowframe,filename = new.filename)
print(paste("FCS file ",i," done", sep = ""))}

# print session information
sessionInfo()
```
