---
title: "T-REX Analysis on RV 001"
author: "Sierra Barone"
date: "07/20/2020"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

## Tracking Responders Expanding 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Data from Barone et al., eLife. 2021 (https://elifesciences.org/articles/64653)


# uncomment lines below to install packages
# install.packages("devtools", repos = "http://cran.us.r-project.org")
# devtools::install_github("cytolab/mem")
# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# install.packages("ggplot2", repos = "http://cran.us.r-project.org")
# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# install.packages("uwot", repos = "http://cran.us.r-project.org")
# install.packages("dbscan", repos = "http://cran.us.r-project.org")
# if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
# BiocManager::install("flowCore")
# BiocManager::install("Biobase")


# load packages
library(flowCore)
library(uwot)
library(FNN)
library(ggplot2)
library(dbscan)
library(MEM)
library(tidyverse)
library(Biobase)

# set working directory 
setwd(paste(getwd(),"/data_files/rhinovirus", sep = ""))

# setup sample and T-REX info
output_filename = "_T-REX"
sample_type = "RV"
sample_id = "001"
time_comparison = "0v7" 
kvalue = 60

# look at files
data.files <-  dir(pattern = "*.fcs")
print(data.files)
# choose index for each timepoint based on order of data.files
first.timepoint = 1
second.timepoint = 2

# combine paired samples
first.timepoint.data = as.data.frame(lapply(lapply(data.files[[1]], read.FCS), exprs))
first.timepoint.data$File_ID = 1
second.timepoint.data = as.data.frame(lapply(lapply(data.files[[2]], read.FCS), exprs))
second.timepoint.data$File_ID = 2
paired.data = rbind(first.timepoint.data,second.timepoint.data)
orig.names <- colnames(paired.data)
colnames(paired.data)[1:length(paired.data) - 1] <- as.character(read.FCS(data.files[[1]])@parameters@data[["desc"]])
```

```{r equal_sampling}
# set seed and equally sample based on limiting sample
set.seed(1)
files.to.sample = split(paired.data,paired.data$`File_ID`)
sampled.data <- list()
for (i in 1: length(files.to.sample)){
    sampled.data[[i]] = as.data.frame(files.to.sample[[i]][sample(nrow(files.to.sample[[i]]), min(sapply(files.to.sample, nrow))), ])}
my.sampled.data = as.data.frame(do.call(rbind, sampled.data))
```

```{r scaling_and_filtering}
# choose markers to make low dimensional projection of the data and scale them accordingly 
#colnames(my.sampled.data)   
my.chosen.sampled.data = my.sampled.data[,c(8:12,14:18,21,25:29,31)]
#colnames(my.chosen.sampled.data) 
transformed.data = as.data.frame(t(apply(my.chosen.sampled.data, 1, function(x) asinh(x/6000))))
colnames(transformed.data) 
umap.input = transformed.data[,c(1:5,7:13,16:17)]
```

```{r UMAP}
setwd(paste(getwd(),"/data_files/rhinovirus", sep = ""))

# run UMAP amd save model
# myumap <- umap(umap.input, ret_model = TRUE, verbose = TRUE)
dir.create("./output files/")
# save_uwot(myumap, paste0(strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"_umap_model_results"))
umap.data <- as.data.frame(cbind(my.sampled.data$UMAP1,my.sampled.data$UMAP2))
colnames(umap.data) <- c("UMAP1", "UMAP2")
```

```{r KNN}
setwd(paste(getwd(),"/data_files/rhinovirus", sep = ""))

# KNN search per cell 
neighbor_index = knnx.index(umap.data,umap.data,k=kvalue)
neighbor_index[neighbor_index <= nrow(umap.data)/2] <- 0
neighbor_index[neighbor_index > nrow(umap.data)/2] <- 1
# calculate percent change in each KNN region
percent_change = (rowSums(neighbor_index) / kvalue * 100)

# binning and plot info
all.data = cbind(my.sampled.data)
range <- apply(apply(umap.data, 2, range), 2, diff)
graphical.ratio <- (range[1] / range[2])
test.round = round(percent_change)
trex.plot <-
  data.frame(x = umap.data[, 1], y = umap.data[, 2], col = test.round)
trex.plot$cuts = cut(trex.plot$col, c(0, 5, 15, 85, 95, 100), include.lowest = TRUE,right = FALSE)
trex.plot$cuts = factor(trex.plot$cuts,
                        levels = c("[15,85)", "[5,15)", "[0,5)", "[85,95)", "[95,100]"))
ordered_plot = trex.plot[order(trex.plot$cuts), ]
range <- apply(apply(umap.data, 2, range), 2, diff)
graphical.ratio <- (range[1] / range[2])

# create T-REX plot
png(
  paste(
    "./output files/",
    strftime(Sys.time(), "%Y-%m-%d_%H%M%S"),
    " blue red TREX plot.png",
    sep = ""
  ),
  res = 200,
  width = 1500,
  height = 1500
)

final_trex_plot <-
  ggplot(ordered_plot) + geom_point(aes(x = x, y = y, colour = cuts), cex = 1) +
  scale_color_manual(
    name = "col",
    values = c(
      "[15,85)" = "lightgray",
      "[5,15)" = "lightskyblue",
      "[0,5)" = "navyblue",
      "[85,95)" = "lightcoral",
      "[95,100]" = "darkred"
    )
  ) +
  theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank()) +
  labs (x = "UMAP1", y = "UMAP2", title = paste(sample_type,"_",sample_id,"_",time_comparison," - Percent Change",sep = "")) + coord_fixed(ratio = graphical.ratio) + theme(legend.title = element_blank()) + 
  labs(caption = "Data from Barone et al., eLife. 2021")

print(final_trex_plot)
dev.off()
final_trex_plot
```
  
```{r trex_results}  
setwd(paste(getwd(),"/data_files/rhinovirus", sep = ""))

# uncomment lines below to plot heat on markers on umap axes
#plot.to.output<-list() 
# for (i in 1:ncol(umap.input)){
#   color.plot <- data.frame(x = umap.data[,1], y = umap.data[,2], col = umap.input[,c(i)])
#   order.plot <- color.plot[order(color.plot$col),]
#   print(ggplot(order.plot)+ geom_point(aes(x= x, y= y, col = col),cex = 0.1,shape = 1) + coord_fixed(ratio=graphical.ratio) + 
#   theme_bw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
#     labs (x = "UMAP1", y = "UMAP2", col = colnames(umap.input)[i])+
#   scale_color_gradientn(
#     colours = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(50)))}

# calculate degree of change and direction of change for individual pairwise comparison
all.data$status <- trex.plot$cuts
sample.table <- data.frame(sample_type,sample_id,time_comparison,total_cells = nrow(umap.data))
sample.table[,c(5:9)]<-summary(trex.plot$cuts)
colnames(sample.table)[5:9]<-c( "(15,85]","(5,15]","[0,5]","(85,95]","(95,100]")
percent = 100*(summary(trex.plot$cuts)/nrow(umap.data))
sample.table$degree_of_change = (sum(percent[3]+percent[5]))
sample.table$direction_of_change = (summary(trex.plot$cuts)[5]-summary(trex.plot$cuts)[3]) / (summary(trex.plot$cuts)[5]+summary(trex.plot$cuts)[3])

write.csv(sample.table, paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"_trex_results.csv"))
print(sample.table)
```

```{r clustering}
setwd(paste(getwd(),"/data_files/rhinovirus", sep = ""))

# use DBSCAN to cluster on regions of great change (5th and 95 percentiles of change)

colnames(all.data)[1:7]<-orig.names[1:7]
regions.of.interest <- all.data %>%
  dplyr::filter(status == "[0,5)" | status == "[95,100]") 
regions.of.interest.umap = cbind(regions.of.interest$UMAP1,regions.of.interest$UMAP2)
a = dbscan::dbscan(regions.of.interest.umap, eps = 0.4,minPts = 1)
cluster = a$cluster 
track.data = cbind(regions.of.interest,cluster)
track.data <- track.data %>%
  filter(cluster!=0)
track.data$cluster[which(track.data$status=="[0,5)")]<-paste0(track.data$cluster[which(track.data$status=="[0,5)")],"05")
track.data$cluster[which(track.data$status=="[95,100]")]<-paste0(track.data$cluster[which(track.data$status=="[95,100]")],"95")
track.data$cluster<-as.numeric(track.data$cluster)

png(paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," DBSCAN_plot.png",sep =""),res = 200, width = 1500, height = 1500)
dbscan_plot <- ggplot(data.frame(x = track.data$UMAP1, 
                   y = track.data$UMAP2, 
                   col = as.factor(track.data$cluster))) + coord_fixed(ratio = graphical.ratio) + 
  geom_point(aes(x=x, y=y, color=col),cex = 1.5) + 
  guides(colour = guide_legend(override.aes = list(size=5), nrow = 13)) +
  labs(x = "UMAP 1", y = "UMAP 2",title = "DBSCAN Clusters (5th & 95th percentiles)", 
       color = "DBSCAN Cluster") + theme_bw() + theme(legend.title = element_blank()) 
print(dbscan_plot)
dev.off()
dbscan_plot
```

```{r MEM}
setwd(paste(getwd(),"/data_files/rhinovirus", sep = ""))

# run MEM on DBSCAN clusters split by 95th and 5th percentiles of change in KNN region
MEM.data = track.data[,c(8:12,14:18,21,25:29,31,ncol(track.data))]
MEM.data = MEM.data[order(MEM.data$cluster),]
MEM.values.KNN = MEM(MEM.data, transform = TRUE, cofactor = 6000,
                     choose.markers = FALSE, markers = "all", choose.ref = FALSE, zero.ref = TRUE, rename.markers = FALSE,
                     new.marker.names = "none", file.is.clust = FALSE, add.fileID = FALSE, IQR.thresh = NULL)
build.heatmaps(MEM.values.KNN, cluster.MEM = "none", cluster.medians = "none",
               display.thresh = 1, newWindow.heatmaps=FALSE, output.files = TRUE, labels = FALSE)
all.clusters = split(track.data,as.factor(track.data$cluster))
counts.total  <- sapply(all.clusters, NROW)
counts.5<-vector()
for (i in 1:length(all.clusters)){
  counts.5[i] = summary(all.clusters[[i]]$status)[3]}
counts.95 = counts.total-counts.5
cluster.data = as.data.frame(counts.total)
colnames(cluster.data)<- "total_counts"
cluster.data$counts_5<-counts.5
cluster.data$counts_95<-counts.95
write.csv(cluster.data,paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," DBSCAN_cluster_percentiles_counts_MEM.csv",sep =""))
print(cluster.data)
```


```{r export_FCS_files}
setwd(paste(getwd(),"/data_files/rhinovirus", sep = ""))

# export new FCS files with sampled data, percent change, and umap axes
to.export = cbind(my.sampled.data,umap.data,percent_change)
desc = colnames(to.export)[-c(ncol(my.sampled.data))]
colnames(to.export)[1:ncol(my.sampled.data)]<-orig.names
separate.fcs.files = split(to.export,to.export$`File_ID`)
for (i in 1:length(separate.fcs.files)){
reduce.data = subset(separate.fcs.files[[i]], select=-c(`File_ID`))
mat.input<- as.matrix(reduce.data)
metadata <- data.frame(name = dimnames(mat.input)[[2]], desc = desc)
metadata$range <- apply(apply(mat.input, 2, range), 2, diff)
metadata$minRange <- apply(mat.input, 2, min)
metadata$maxRange <- apply(mat.input, 2, max)
input.flowframe <- new("flowFrame", exprs=mat.input,parameters = AnnotatedDataFrame(metadata))  
newname  = str_remove(data.files[i], ".fcs")
new.filename = paste0("./output files/",newname,"_T-REX.fcs",sep="")
write.FCS(input.flowframe,filename = new.filename)
print(paste("FCS file ",i," done", sep = ""))}

# print session information
sessionInfo()
```


```{r tetra plot}
setwd(paste(getwd(),"/data_files/rhinovirus", sep = ""))


pos.1 <- which(my.sampled.data$`Tetra1`>18000 & my.sampled.data$`Tetra2`<18000 & my.sampled.data$`Tetra3`<18000)
pos.3 <- which(my.sampled.data$`Tetra1`<18000 & my.sampled.data$`Tetra2`<18000 & my.sampled.data$`Tetra3`>18000)
pos.2 <- which(my.sampled.data$`Tetra1`<18000 & my.sampled.data$`Tetra2`>18000 & my.sampled.data$`Tetra3`<18000)
tetrapos.cells = c(pos.1,pos.2,pos.3)

neighbor_index = knnx.index(umap.data,umap.data,k=kvalue)
tetra.pos.knn = which(matrix(neighbor_index %in% tetrapos.cells, dim(neighbor_index)), arr.ind = T) 
neighbor_index[tetra.pos.knn]<-1
neighbor_index[neighbor_index != 1] <- 0
total.tetra.count = (rowSums(neighbor_index)/kvalue*100)

pdf(paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," box and whisker 1 percent.pdf"),width=5)
# 1% binning all 
test.round = round(percent_change)
data.to.plot = as.data.frame(cbind(test.round,total.tetra.count))
data.to.plot$test.round<- as.factor(data.to.plot$test.round)
print(ggplot(data.to.plot, aes(x = test.round, y = total.tetra.count)) + 
  geom_boxplot(outlier.shape = NA, fill="gray")  + labs(x=paste("% change in KNN region k=",kvalue), y = "% Tetramer+ in KNN region")+ theme_classic())
dev.off()

for (i in c(5)){
  
all.data$status <- 0
data.to.plot = as.data.frame(cbind(test.round,total.tetra.count))

png(paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," UMAP_plot_percent_change_95.png") ,res = 200,
  width = 1500,
  height = 1500
)
all.data$status <- 0
indices.post.enriched = which(test.round>=95)
all.data[indices.post.enriched,]$status <- 1
indices.post.enriched.tetra = which(data.to.plot$test.round>=95 & data.to.plot$total.tetra.count>=i)
all.data[indices.post.enriched.tetra,]$status <- 2
cols <- c("0" = "lightgray","1" = "darkred","2" = "deeppink")
all.data.ordered <- all.data[order(all.data$status),]
plot <- data.frame(x = all.data.ordered$UMAP1, y = all.data.ordered$UMAP2, col = as.factor(all.data.ordered$status))
clinical_clusters <- ggplot(plot)+ geom_point(aes(x = all.data.ordered$UMAP1, y = all.data.ordered$UMAP2, col = as.factor(all.data.ordered$status))) + scale_color_manual(values = cols, labels = c("does not pass % change cutoff",paste0("passes % change cutoff, tet- (",summary(as.factor(all.data.ordered$status))[2]," cells)"), paste0("passes % change cutoff, tet+ (",summary(as.factor(all.data.ordered$status))[3]," cells)")), name = element_blank())+
  guides(colour = guide_legend(override.aes = list(size=5)))+ theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + labs (x = "UMAP1", y = "UMAP2", title = paste0("% change above 95, % tetra+ at ",i)) + coord_fixed(ratio=graphical.ratio)
print(clinical_clusters)
dev.off()

png(paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," UMAP_plot_tet_change_95.png"),res = 200,
  width = 1500,
  height = 1500)
all.data$status <- 0
indices.post.enriched.tetra = which(data.to.plot$test.round>=95 & data.to.plot$total.tetra.count>=i)
all.data[indices.post.enriched.tetra,]$status <- 2
indices.tetra = which(data.to.plot$test.round<95 & data.to.plot$total.tetra.count>=i)
all.data[indices.tetra,]$status <- 1
cols <- c("0" = "lightgray", "1" = "purple", "2" = "deeppink")
all.data.ordered <- all.data[order(all.data$status),]
plot <- data.frame(x = all.data.ordered$UMAP1, y = all.data.ordered$UMAP2, col = as.factor(all.data.ordered$status))
clinical_clusters <- ggplot(plot)+ geom_point(aes(x = all.data.ordered$UMAP1, y = all.data.ordered$UMAP2, col = as.factor(all.data.ordered$status))) + scale_color_manual(values = cols,labels = c("tet-",paste0("does not pass % change cutoff, tet+ (",summary(as.factor(all.data.ordered$status))[2]," cells)"),paste0("passes % change cutoff, tet+ (",summary(as.factor(all.data.ordered$status))[3]," cells)")), name = element_blank())+ theme_bw() +
  guides(colour = guide_legend(override.aes = list(size=5)))+ theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ labs (x = "UMAP1", y = "UMAP2", title = paste0("% change at 95, % tetra+ at ",i)) + coord_fixed(ratio=graphical.ratio)
print(clinical_clusters)
dev.off()

}

```
