---
title: "T-REX Analysis on AML Data"
author: "Sierra Barone"
contributors: "Claire Cross, and Cass Mayeda"
date: "09/02/2022"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

## Tracking Responders Expanding 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Data from Ferrell et al., PLOS One. 2016 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4830605/)

# uncomment lines below to install packages
# if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
# BiocManager::install("cytoMEM")
# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# install.packages("ggplot2", repos = "http://cran.us.r-project.org")
# install.packages("FNN", repos = "http://cran.us.r-project.org")
# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# install.packages("uwot", repos = "http://cran.us.r-project.org")
# install.packages("dbscan", repos = "http://cran.us.r-project.org")
# if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
# BiocManager::install("flowCore")
# BiocManager::install("Biobase")


# load packages
library(flowCore)
library(uwot)
library(FNN)
library(ggplot2)
library(dbscan)
library(cytoMEM)
library(tidyverse)
library(Biobase)
library(RColorBrewer)
library(dplyr)
library(purrr)
library(cowplot)

# load T-REX functions from local folder 
source("R/TREX.R")

# make directory to save output files in 
setwd(paste0(getwd(),"/data_files/aml"))
dir.create("TREX_output")
```

```{r read in files}
# set working directory 
setwd(paste0(getwd(),"/data_files/aml"))

data.filenames = dir(pattern = "*.fcs")
first.dataset = as.data.frame(lapply(lapply(data.filenames[[1]], read.FCS), exprs))
first.dataset$file_ID = 1
second.dataset = as.data.frame(lapply(lapply(data.filenames[[2]], read.FCS), exprs))
second.dataset$file_ID = 2

# save original column names for final export to FCS files 
orig.names = colnames(first.dataset)
```

```{r equal sampling}
# find number of datapoints in smaller sample 
smaller_sample = nrow(first.dataset) 
if (nrow(second.dataset) < smaller_sample) { 
  smaller_sample <- nrow(second.dataset) 
}

set.seed(1)

# get an equal number of datapoints from both datasets 
sampled.data = as.data.frame(rbind(
  first.dataset[sample(nrow(first.dataset), smaller_sample), ], 
  second.dataset[sample(nrow(second.dataset), smaller_sample), ]
))

# rename columns with simplified marker names
setwd(paste0(getwd(),"/data_files/aml"))
colnames(sampled.data)[1:(length(sampled.data) - 2)] <- as.character(read.FCS(data.files[[1]])@parameters@data[["desc"]])
```

```{r choose markers, scale data}
# choose markers to make low dimensional embedding 
chosen.data = sampled.data[, c(5:31)]

# scale data 
transformed.data = as.data.frame(t(apply(chosen.data, 1, function(x) asinh(x/15))))
```

```{r UMAP}
setwd(paste0(getwd(),"/data_files/aml"))

# create UMAP (low dimensional embedding)
myumap <- umap(transformed.data, ret_model = TRUE, verbose = TRUE)

# uncomment the line below to save the UMAP 
#save_uwot(myumap, paste0(strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"_umap_model_results"))

umap.data = as.data.frame(myumap$embedding)
colnames(umap.data) <- c("UMAP1", "UMAP2")
```

```{r marker heatmaps}  
setwd(paste0(getwd(),"/data_files/aml"))

umap.bychannel <- as_tibble(umap.data) %>%
  bind_cols(transformed.data)  %>%
  gather(channel, intensity, -UMAP1, -UMAP2) %>%
  mutate(across(channel,factor))%>%
  group_split(channel) %>%
  map(
    ~ggplot(., aes(x = UMAP1, y = UMAP2, col = intensity)) +
      geom_point(shape = ".", size = 8) +
      scale_color_gradientn(
        colours = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(5)) +
      facet_grid(~ channel, labeller = function(x) label_value(x, multi_line = FALSE)) +
      coord_fixed() +
      theme_bw() +
      theme(
        strip.text.x = element_text(size = 20),
        legend.title = element_blank(),
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()
      )
    ) %>%
  plot_grid(plotlist = ., align = 'hv', ncol = 8)

png(paste(strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"UMAP on transformed data.png"),height = 2000,width = 4000)
print(umap.bychannel)
dev.off()
```

```{r TREX}
setwd(paste0(getwd(),"/data_files/aml/TREX_output"))

my.binned = TREX(cbind(umap.data, sampled.data$file_ID))

TREX_plot(my.binned, embed.type = "UMAP")
```

```{r TREX results}
setwd(paste0(getwd(),"/data_files/aml/TREX_output"))
TREX_stats(my.binned)
```

```{r clustering}
setwd(paste0(getwd(),"/data_files/aml/TREX_output"))

# use DBSCAN to cluster on regions of great change (5th and 95 percentiles of change)
my.clusters = TREX_cluster(
  my.binned,
  db.eps = 0.3,
  marker.data = sampled.data[, c(5:31)]
)

TREX_cluster_plot(
  my.clusters,
  my.binned,
  embed.type = "UMAP"
)
```

```{r MEM}
setwd(paste0(getwd(),"/data_files/aml"))

# run MEM on DBSCAN clusters
MEM.input = my.clusters[, c(5:ncol(my.clusters))]
MEM.input <- MEM.input[order(MEM.input$cluster), ]
MEM.output = MEM(
  MEM.input, 
  transform = TRUE, 
  cofactor = 15,
  zero.ref = TRUE, 
  new.marker.names = "CD235a,CD19,CD117,CD11b,CD4,CD64,CD7,CD34,CD61,CD123,CD13,CD62L,CD45,CD183,CD33,CD11c,CD14,CD15,CD16,CD24,CD38,CD25,CD3,CD185,HLA-DR,CD184,CD56", 
  scale.matrix = "arcsinh",
  scale.factor = 1
)

build_heatmaps(
  MEM.output, 
  cluster.MEM = "none",
  output.files = TRUE, 
)

```

```{r count cells in each cluster}
setwd(paste0(getwd(),"\data_files\aml\TREX_output"))

all.clusters = split(track.data,as.factor(track.data$cluster))
counts.total  <- sapply(all.clusters, NROW)
counts.5<-vector()
for (i in 1:length(all.clusters)){
  counts.5[i] = sum(all.clusters[[i]][["status"]] == '[0,5]')}
counts.95 = counts.total-counts.5
cluster.data = as.data.frame(counts.total)
colnames(cluster.data)<- "total_counts"
cluster.data$counts_5<-counts.5
cluster.data$counts_95<-counts.95
write.csv(cluster.data,paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S")," DBSCAN_cluster_percentiles_counts_MEM.csv",sep =""))
print(cluster.data)
```

```{r export_FCS_files}
setwd(paste(getwd(),"/data_files/aml", sep = ""))

# export new FCS files with sampled data, percent change, and umap axes
to.export = cbind(my.sampled.data,umap.data,percent_change)
desc = colnames(to.export)[-c(ncol(my.sampled.data),(ncol(my.sampled.data)-1))]
colnames(to.export)[1:ncol(my.sampled.data)]<-orig.names
separate.fcs.files = split(to.export,to.export$`orig_ID`)
for (i in 1:length(separate.fcs.files)){
reduce.data = subset(separate.fcs.files[[i]], select=-c(`File_ID`,`orig_ID`))
mat.input<- as.matrix(reduce.data)
metadata <- data.frame(name = dimnames(mat.input)[[2]], desc = desc)
metadata$range <- apply(apply(mat.input, 2, range), 2, diff)
metadata$minRange <- apply(mat.input, 2, min)
metadata$maxRange <- apply(mat.input, 2, max)
input.flowframe <- new("flowFrame", exprs=mat.input,parameters = AnnotatedDataFrame(metadata))  
newname  = str_remove(data.files[i], ".fcs")
new.filename = paste0("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"_",newname,"_T-REX.fcs",sep="")
write.FCS(input.flowframe,filename = new.filename)
print(paste("FCS file ",i," done", sep = ""))}

# print session information
sessionInfo()
```
